### ISSUE TITLE
v0.110.0 broke something with Editor Components?

### ISSUE THREAD

**Issue by m4rrc0** [sveltia/sveltia-cms#523]
Hey.

Weird bug... Editor Components are added twice. So does data in lists inside Editor Components + data is not properly recovered and injected into the UI when editing Editor Components.

I don't have the issue on v0.109.1

I am testing this with CDN import from unpkg.

**Comment by kyoshino** [comment]
Hmm, will check.

**Comment by kyoshino** [comment]
Fixed in [v0.110.1](https://github.com/sveltia/sveltia-cms/releases/tag/v0.110.1) 🙇🏼

**Comment by m4rrc0** [comment]
Thanks! The 'double injection' seems resolved.

Still have issues with relation fields in Editor Components though.

**Comment by kyoshino** [comment]
> Still have issues with relation fields in Editor Components though.

What issue?

**Comment by kyoshino** [comment]
I have realized that checkboxes and radio buttons are broken in another app using Sveltia UI, so I just fixed the issue and shipped [v0.110.2](https://github.com/sveltia/sveltia-cms/releases/tag/v0.110.2).

**Comment by m4rrc0** [comment]
> I have realized that checkboxes and radio buttons are broken in another app using Sveltia UI, so I just fixed the issue and shipped [v0.110.2](https://github.com/sveltia/sveltia-cms/releases/tag/v0.110.2).

💯 Spot on. That was the issue! Thanks!
